name: flutter_application_1
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  images_picker: ^1.2.11
  scan: ^1.6.0
  pay: ^1.1.0
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  cloud_firestore: ^4.5.2
  firebase_dynamic_links: ^5.2.0
  provider: ^6.0.5
  go_router: ^7.1.1
  combined_barcode_scanner: ^0.0.1-dev.1
  qr_code_dart_scan: ^0.7.1
  qr_bar_code_scanner_dialog: ^0.0.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0

flutter:
  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
