// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnci3HPEO3aWSsqUoyOl4rRAKSVAaqUK8',
    appId: '1:561007978899:web:105530050a706e2a3b6066',
    messagingSenderId: '561007978899',
    projectId: 'soldout-81e6f',
    authDomain: 'soldout-81e6f.firebaseapp.com',
    databaseURL: 'https://soldout-81e6f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'soldout-81e6f.appspot.com',
    measurementId: 'G-FRZGBC53K1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA9BYjZmTBCcvH21RgNQjhCP6ntJIC_sk',
    appId: '1:561007978899:android:49cf3bdc05cb27f03b6066',
    messagingSenderId: '561007978899',
    projectId: 'soldout-81e6f',
    databaseURL: 'https://soldout-81e6f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'soldout-81e6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL7AmprFgdhcMv2m6ajV1vD4RvGC-WeMc',
    appId: '1:561007978899:ios:b13de3654e692ab93b6066',
    messagingSenderId: '561007978899',
    projectId: 'soldout-81e6f',
    databaseURL: 'https://soldout-81e6f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'soldout-81e6f.appspot.com',
    iosClientId: '561007978899-6daip3hdgv7215gt3ij247bignkes70i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL7AmprFgdhcMv2m6ajV1vD4RvGC-WeMc',
    appId: '1:561007978899:ios:ef60012a99e1ea433b6066',
    messagingSenderId: '561007978899',
    projectId: 'soldout-81e6f',
    databaseURL: 'https://soldout-81e6f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'soldout-81e6f.appspot.com',
    iosClientId: '561007978899-g77k8dambhq44k8tp4a90ld7lmcuue86.apps.googleusercontent.com',
    iosBundleId: 'com.example.soldout.RunnerTests',
  );
}
